AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - config/**/*
    - bin/*
    - app/admin/auth/*
    - spec/*_helper.rb

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 80

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
