scss_files: 'app/frontend/css/**/*.scss'

linters:
  StringQuotes:
    style: 'double_quotes'
  QualifyingElement:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false

  
  

  
  
